### ISSUE TITLE
Add Open in Gitpod button

### ISSUE THREAD

**Issue by jsstrn** [tdd-workshops/tdd-lab-nodejs-jest#1]
According to Gitpod's [documentation](https://www.gitpod.io/docs/configuration/), we can add a badge and/or button in the README file to open the project in Gitpod. 

If the intention is to allow workshop participants to use this code base as a template and run it on Gitpod, perhaps having a button to quickly launch the project in Gitpod would be helpful. 

If we think this is useful, I could add the button and create a pull-request for this and all other starter projects listed. 

Here's what the badge looks like: 
[![Gitpod Ready-to-Code](https://img.shields.io/badge/Gitpod-ready--to--code-blue?logo=gitpod)](https://gitpod.io/#https://github.com/<your-org>/<your-project>)

Here's what the quick start button looks like: 
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/<your-org>/<your-project>)

Reference: [Configuring your project](https://www.gitpod.io/docs/configuration/)

**Comment by miccheng** [comment]
I tried but it means the GitPod Workspace will be linked to the github org hard coded there... I plan to get folks to fork the repo so they can commit to it.

**Comment by jsstrn** [comment]
Makes sense. I'll close this.
